nameSuffix: "-two"
bases:
  - ../base
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx
  path: patch.yaml

configMapGenerator:
- name: nginx-cm
  literals:
  - VAR_M=value_m
  - VAR_U=value_u
  - VAR_L=value_l
~                     