nameSuffix: "-one"
bases:
  - ../base
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx
  path: patch.yaml

configMapGenerator:
- name: nginx-cm
  literals:
  - VAR_Z=value_z
  - VAR_Y=value_y
  - VAR_W=value_w
~                     