apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: nginx
        env:
          - name: VAR_A
            value: "value_a_for_one"
          - name: VAR_B
            value: "value_b_for_one"
          - name: VAR_C
            value: "value_c_for_one"

