apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
          - name: VAR_A
            value: "value_a"
          - name: VAR_B
            value: "value_b"
          - name: VAR_D
            value: "value_d"
        envFrom:
          - configMapRef:
              name: nginx-cm

